[package]
name = "teamruns_client"
version = "0.11.0"
description = "Teamruns Multiplayer Client"
authors = ["Dexz"]
edition = "2021"
repository = "https://github.com/JoKronk/teamruns-client"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
semver = "1.0.24"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.27", features = ["derive"] }
strum_macros = "0.27.2"
ts-rs = "11.0"
thiserror = "2.0.15"
log = "0.4.21"
rustc-serialize = "0.3"
fs_extra = "1.3.0"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
flate2 = "1.1.2"
tar = "0.4.43"
zip-extract = "0.3.0"
chrono = "0.4.39"
fern = { version = "0.7.1", features = ["date-based", "colored"] }
tauri-codegen = "2.5.0"
tauri-plugin = "2.5.3"
tauri-plugin-opener = "2.5.3"
tauri-plugin-process = "2.3.1"
tauri-plugin-notification = "2.3.3"
tauri-plugin-fs = "2.5.0"
tauri-plugin-shell = "2.3.5"
tauri-plugin-http = "2.5.3"
tauri-plugin-clipboard-manager = "2.3.2"
tauri-plugin-dialog = "2.5.3"
tauri-plugin-os = "2.3.2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
