import { Task } from "./task";

export class TaskSplit {
    gameTask: string;
    name: string | undefined;
    enabled: boolean;

    constructor(gameTask: string) {
        this.gameTask = gameTask;
        this.name = Task.defaultSplitName(gameTask);
        this.enabled = true;
    }

    static generateDefaultSplitList(): TaskSplit[] {
        let splits: TaskSplit[] = [];
        splits.push(new TaskSplit("training-gimmie"));
        splits.push(new TaskSplit("training-door"));
        splits.push(new TaskSplit("training-climb"));
        splits.push(new TaskSplit("training-buzzer"));
        splits.push(new TaskSplit("village1-mayor-money"));
        splits.push(new TaskSplit("village1-uncle-money"));
        splits.push(new TaskSplit("village1-yakow"));
        splits.push(new TaskSplit("village1-oracle-money1"));
        splits.push(new TaskSplit("village1-oracle-money2"));
        splits.push(new TaskSplit("village1-buzzer"));
        splits.push(new TaskSplit("beach-ecorocks"));
        splits.push(new TaskSplit("beach-flutflut"));
        splits.push(new TaskSplit("beach-pelican"));
        splits.push(new TaskSplit("beach-seagull"));
        splits.push(new TaskSplit("beach-cannon"));
        splits.push(new TaskSplit("beach-gimmie"));
        splits.push(new TaskSplit("beach-sentinel"));
        splits.push(new TaskSplit("beach-buzzer"));
        splits.push(new TaskSplit("jungle-lurkerm"));
        splits.push(new TaskSplit("jungle-tower"));
        splits.push(new TaskSplit("jungle-eggtop"));
        splits.push(new TaskSplit("jungle-plant"));
        splits.push(new TaskSplit("jungle-fishgame"));
        splits.push(new TaskSplit("jungle-canyon-end"));
        splits.push(new TaskSplit("jungle-temple-door"));
        splits.push(new TaskSplit("jungle-buzzer"));
        splits.push(new TaskSplit("misty-muse"));
        splits.push(new TaskSplit("misty-boat"));
        splits.push(new TaskSplit("misty-cannon"));
        splits.push(new TaskSplit("misty-warehouse"));
        splits.push(new TaskSplit("misty-bike"));
        splits.push(new TaskSplit("misty-bike-jump"));
        splits.push(new TaskSplit("misty-eco-challenge"));
        splits.push(new TaskSplit("misty-buzzer"));
        splits.push(new TaskSplit("firecanyon-end"));
        splits.push(new TaskSplit("firecanyon-buzzer"));
        splits.push(new TaskSplit("village2-gambler-money"));
        splits.push(new TaskSplit("village2-geologist-money"));
        splits.push(new TaskSplit("village2-warrior-money"));
        splits.push(new TaskSplit("village2-oracle-money1"));
        splits.push(new TaskSplit("village2-oracle-money2"));
        splits.push(new TaskSplit("village2-buzzer"));
        splits.push(new TaskSplit("sunken-room"));
        splits.push(new TaskSplit("sunken-pipe"));
        splits.push(new TaskSplit("sunken-slide"));
        splits.push(new TaskSplit("sunken-sharks"));
        splits.push(new TaskSplit("sunken-platforms"));
        splits.push(new TaskSplit("sunken-top-of-helix"));
        splits.push(new TaskSplit("sunken-spinning-room"));
        splits.push(new TaskSplit("sunken-buzzer"));
        splits.push(new TaskSplit("swamp-flutflut"));
        splits.push(new TaskSplit("swamp-billy"));
        splits.push(new TaskSplit("swamp-battle"));
        splits.push(new TaskSplit("swamp-tether-1"));
        splits.push(new TaskSplit("swamp-tether-2"));
        splits.push(new TaskSplit("swamp-tether-3"));
        splits.push(new TaskSplit("swamp-tether-4"));
        splits.push(new TaskSplit("swamp-buzzer"));
        splits.push(new TaskSplit("rolling-moles"));
        splits.push(new TaskSplit("rolling-robbers"));
        splits.push(new TaskSplit("rolling-race"));
        splits.push(new TaskSplit("rolling-lake"));
        splits.push(new TaskSplit("rolling-plants"));
        splits.push(new TaskSplit("rolling-ring-chase-1"));
        splits.push(new TaskSplit("rolling-ring-chase-2"));
        splits.push(new TaskSplit("rolling-buzzer"));
        splits.push(new TaskSplit("ogre-boss"));
        splits.push(new TaskSplit("ogre-end"));
        splits.push(new TaskSplit("ogre-secret"));
        splits.push(new TaskSplit("ogre-buzzer"));
        splits.push(new TaskSplit("village3-miner-money1"));
        splits.push(new TaskSplit("village3-miner-money2"));
        splits.push(new TaskSplit("village3-miner-money3"));
        splits.push(new TaskSplit("village3-miner-money4"));
        splits.push(new TaskSplit("village3-oracle-money1"));
        splits.push(new TaskSplit("village3-oracle-money2"));
        splits.push(new TaskSplit("village3-extra1"));
        splits.push(new TaskSplit("village3-buzzer"));
        splits.push(new TaskSplit("snow-eggtop"));
        splits.push(new TaskSplit("snow-ram"));
        splits.push(new TaskSplit("snow-bumpers"));
        splits.push(new TaskSplit("snow-cage"));
        splits.push(new TaskSplit("snow-fort"));
        splits.push(new TaskSplit("snow-ball"));
        splits.push(new TaskSplit("snow-bunnies"));
        splits.push(new TaskSplit("snow-buzzer"));
        splits.push(new TaskSplit("cave-gnawers"));
        splits.push(new TaskSplit("cave-dark-crystals"));
        splits.push(new TaskSplit("cave-dark-climb"));
        splits.push(new TaskSplit("cave-robot-climb"));
        splits.push(new TaskSplit("cave-swing-poles"));
        splits.push(new TaskSplit("cave-spider-tunnel"));
        splits.push(new TaskSplit("cave-platforms"));
        splits.push(new TaskSplit("cave-buzzer"));
        splits.push(new TaskSplit("lavatube-end"));
        splits.push(new TaskSplit("lavatube-buzzer"));
        splits.push(new TaskSplit("citadel-sage-blue"));
        splits.push(new TaskSplit("citadel-sage-red"));
        splits.push(new TaskSplit("citadel-sage-yellow"));
        splits.push(new TaskSplit("citadel-sage-green"));
        splits.push(new TaskSplit("citadel-buzzer"));
        splits.push(new TaskSplit("finalboss-movies"));
        return splits;
    }
}